version: '3.2'
services:
  
  # SyncThing
  syncthing:
    image: lsioarmhf/syncthing
    deploy:
      mode: global
      placement:
        constraints: 
        - node.role == manager
    restart: always
    ports:
      - target: 8384
        published: 8384
        mode: host
      - target: 22000
        published: 22000
        mode: host
      - target: 21027
        published: 21027
        protocol: udp
        mode: host
    volumes:
      - "/opt/syncthing/config:/config"
      - "/opt/syncthing/data:/data"
#  # Deluge
#  deluge:
#    image: lsioarmhf/deluge
#    restart: always
#    ports:
#      - "6379"
#    volumes:
#      - "/config"
#      - "/downloads"
#
#  # nzbget
#  nzbget:
#    image: lsioarmhf/nzbget
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "6789:6789"
#    volumes:
#      - "/config"
#      - "/downloads"
#
#  # Jackett
#  jackett:
#    image: lsioarmhf/jackett
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "9117:9117"
#    volumes:
#      - "/config"
#      - "/downloads"
#
#  # Cardigann
#  cardigann:
#    image: lsioarmhf/cardigann
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "5060:5060"
#    volumes:
#      - "/config"
#
#  # Sonarr
#  sonarr:
#    image: lsioarmhf/sonarr
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "8989:8989"
#    volumes:
#      - "/config"
#      - "/tv"
#      - "/downloads"
#
#  # Radarr
#  radarr:
#    image: lsioarmhf/radarr
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "7878:7878"
#    volumes:
#      - "/config"
#      - "/movies"
#      - "/downloads"
#
#  # Couchpotato
#  couchpotato:
#    image: lsioarmhf/couchpotato
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "5050:5050"
#    volumes:
#      - "/config"
#      - "/movies"
#      - "/downloads"
#
#  # mylar
#  mylar:
#    image: lsioarmhf/mylar
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "8090:8090"
#    volumes:
#      - "/config"
#      - "/comics"
#      - "/downloads"
#
#  # Headphones
#  headphones:
#    image: lsioarmhf/headphones
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "8081:8081"
#    volumes:
#      - "/config"
#      - "/music"
#      - "/downloads"
#
#  # Headphones
#  beets:
#    image: lsioarmhf/beets
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "1234:1234"
#    volumes:
#      - "/config"
#      - "/music"
#      - "/downloads"
#
#  # Ombi (plexrequests)
#  ombi:
#    image: lsioarmhf/ombi
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "3579:3579"
#    volumes:
#      - "/config"
#
#  # PlexPy
#  plexpy:
#    image: lsioarmhf/plexpy
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "8181:8181"
#    volumes:
#      - "/config"
#      - "$PLEX_LOG_PATH:/logs:ro"
#
#  # htpcmanager
#  htpcmanager:
#    image: lsioarmhf/htpcmanager
#    environment:
#      - TZ=EST
#    restart: always
#    ports:
#      - "8085:8085"
#    volumes:
#      - "/config"
